### ISSUE TITLE
Win10 deatched window not working

### ISSUE THREAD

**Issue by xconstarx** [mrvnklm/homeassistant-desktop#10]
Moin moin Aufgrund der Screens nehme ich mal an man versteht deutsch. Aber für leute die Nachschlagen erstmal die english Variante: 

Hello, I have started to use the app and so far I find it very practical.  But unfortunately the "detached windows" do not work for me.

When I select the option the window opens but I can't click on anything. Actually I can't do anything except change and move the window in windowmode and fullscreen. But I can't resize it or interact with the HassUI. Without detached windows everything works as desired.

Off-Topic: Is there a way to change the window size for the not detached windows? I would like it a little longer/higher.

German: 
Hallo, ich habe angefangen die App zu nutzen und find sie bisher schon mal super praktisch.  Doch leider funktionieren die "detached Windows" bei mir nicht.

Wenn ich die Option auswähle öffnet sich zwar das Fenster aber ich kann nichts anclicken. Eigentlich kann ich nichts außer das Fenster in Windowmode und Fullscreen wechseln und verschieben. Aber keine Größe ändern oder mit der HassUI interagieren. Ohne detached windows funktioniert alles wie gewünscht.

Off-Topic: Gibt es eine Möglichkeit die Fenstergröße für die nicht detached zu ändern? Ich hätte es gerne etwas länger/höher.

Güße

**Comment by mrvnklm** [comment]
Ja, ich komme aus Deutschland but to maximize understandability I will continue using english!
Actually that is a major bug, which I didn't encounter because I never tested the detached window on windows. Somehow the behavior is different to macOS.
I will look into this soon and release an update!
