### ISSUE TITLE
Window size resets to really tiny regularly 

### ISSUE THREAD

**Issue by hannesbe** [mrvnklm/homeassistant-desktop#11]
The window size resets to a very tiny size regularly. I can drag the corner to resize it, but soon thereafter, it resets back to this tiny window. I'm not entirely sure, but I suspect it resets after each reboot, or re-login into Windows.
![image](https://user-images.githubusercontent.com/10950856/97043488-d93c6100-1572-11eb-85d6-856408aa8b96.png)

**Comment by mrvnklm** [comment]
Okay, on macOS is never had that issue and even after looking at the code, I have no idea what could cause the problem. Anything else is the same, just the window size is messed up?
Did you use the installer or the standalone binary?
