### ISSUE TITLE
HTTPS connection not working

### ISSUE THREAD

**Issue by MervinKoops** [mrvnklm/homeassistant-desktop#12]
I'm trying to get a connection to homeassistant on my local network via https://, however it's not being recognized as a valid URL and i'm not getting the login prompt window (it is working via the browser on my computer).  It did work before i switched to SSL.

Version: 1.3.1
OS: Windows 10 Pro x64 v2004
Steps to reproduce: 
 1. Install and open homeassistant-desktop
 2. Try to connect to a home assistant server that is configured to use SSL (typing in a URL starting with https:// with or without a port specified)
Result: Login prompt windows does not show up

It might be related to it being a self-signed SSL certificate?

**Comment by MervinKoops** [comment]
Solved, needed to set up a dns entry and use the domain name instead of the IP address, i think it got stuck on a COMMON_NAME_INVALID error

**Comment by VNRARA** [comment]
How did you set that up?

**Comment by MervinKoops** [comment]
by either using your own DNS server that resolves a domain name of your choice to the IP of your homeassistant box
or by adding an override in the 'hosts' file of the machine that you run 'homeassistant-desktop' on. And then filling in the domain name instead of an IP in 'homeassistant-desktop' since it does not accept an IP address (it tries to verify if it's a valid domain).

**Comment by VNRARA** [comment]
i found that I had to setup the yaml with a reference to the same certs used in kemp and cloudflare and add those to the correct location

**Comment by emphasize** [comment]
which yaml and what is the "correct location"? Mine is resolving fine in the browser (after the addition to host), so i would guess it's a selfsigned problem.
