### ISSUE TITLE
Windows 10: default window height too large and cannot be resized

### ISSUE THREAD

**Issue by sharkyP** [mrvnklm/homeassistant-desktop#17]
Upon installing on my laptop the initial window height exceeds the height of my screen and I am unable to resize the window due to the top border being off screen.

Additionally, when I attempt to resize from the bottom of the window (which is unexpected behaviour) it causes the program to hang or crash

**Comment by mrvnklm** [comment]
Might be fixed, closing this for now.

**Comment by Thib1404** [comment]
This issue still exists, but with width on my side. 
For information I have a 4k display and the problem happens when the resolution is set to 3840x2160 (and scaling to 225% if it helps). This issue doesn't happen when the resolution is set to 1920x1080.
