### ISSUE TITLE
For some reason the language shows up as Chinese ? 

### ISSUE THREAD

**Issue by chansters** [mrvnklm/homeassistant-desktop#2]
I have been enjoying your app these past few weeks but for some reason, the UI has switched to Chinese ?  I just re-downloaded the latest release (1.2.1) and it's still doing that.  Any suggestions on how I can change it back to English ? 

<img width="532" alt="Home Assistant 2020-05-29 01-14-57" src="https://user-images.githubusercontent.com/8441205/83237501-dbc49700-a149-11ea-8827-3f3979eb4c84.png">

**Comment by alexander-mikhnov** [comment]
For me the login window has loaded in Russian when I started the app for the first time. After I have logged in it was English as my HA is actually configured. Russian is indeed my mother tongue, but my system (Windows 10) is in English and the regional settings are German.

**Comment by mrvnklm** [comment]
I spend some time looking into this and found out that the language is either your preferred / first place system or browser language. ([See here](https://community.home-assistant.io/t/login-screen-is-in-russian-why/150283))
Electron doesn't provide an option to enforce the browser to use a specific language, so there is nothing I can do about it.
