### ISSUE TITLE
Ability to edit Instances

### ISSUE THREAD

**Issue by adriansnyman** [mrvnklm/homeassistant-desktop#25]
I added an instance without the "http" prefix.
going to the front of the url - added http, and before I could add :// .. the instance added - but then fails connection

Would like to be able to edit the instances / remove instances

**Comment by mrvnklm** [comment]
Yes, that would be a nice feature, unfortunately I don't have the time atm, but feel free to open a PR.
You can reset the application to reset the instances as a workaround.
