### ISSUE TITLE
Increasing the width error

### ISSUE THREAD

**Issue by holdestmade** [mrvnklm/homeassistant-desktop#3]
When increasing the width of the window past a certain point, the window "slides" to the left off the screen and cannot be resized back as the left of the window if off the screen

**Comment by mrvnklm** [comment]
Can you make a little video showing the issue? On macOS I can recommend [Kap](https://getkap.co)

**Comment by mrvnklm** [comment]
If it is not fixed, I added the possibility to only reset the window positions / sizes in `Reset Application...` menu!
