### ISSUE TITLE
Resize horizontally

### ISSUE THREAD

**Issue by PawelTwardawa** [mrvnklm/homeassistant-desktop#37]
During horizontal resizing app in standard mode (not detached), app moving to different position when right border is near (or equals) end of screen.

**Comment by PawelTwardawa** [comment]
After debugging this problem i found that it is caused by "electron-traywindow-positioner" package. Method _calculateXAlign change window alignment depend on width.

**Comment by VNRARA** [comment]
QQ: will this also fix the jerking and glitching when resizing it?

**Comment by PawelTwardawa** [comment]
>  QQ: will this also fix the jerking and glitching when resizing it?

Yes, it should fix.
