### ISSUE TITLE
Desktop notifications for persistent notifications

### ISSUE THREAD

**Issue by FiftyFour7250** [mrvnklm/homeassistant-desktop#39]
Hey. I beg you, please add desktop notifications for persistent notifications. Because now, if a persistent notification comes, I can't find out about it in any way, only manually open HA, and check it. I don't know, maybe use Windows notifications for this? Although, I think it will be much better if the application has its own notifications, something like this
![NdJ6tRV6YDc](https://user-images.githubusercontent.com/78786088/127779858-2079a661-316d-4718-9f93-9e6239a73e51.jpg)

**Comment by tgcowell** [comment]
It would be great if the app was able to benefit from notifications, perhaps that might be coming in V2?

**Comment by mrvnklm** [comment]
I will look into that!
