### ISSUE TITLE
[FEATURE] Only zoom maps with modifier key

### ISSUE THREAD

**Issue by marcselman** [mrvnklm/homeassistant-desktop#48]
I have a map visible but when scrolling, when I reach the map, the map starts zooming instead of scrolling the rest of the page. Google Maps has solved that by requiring an extra click or holding a modifier key or something to interact with the map. I assume this is Home Assistant itself and you can't control that, but who knows ;)

**Comment by mrvnklm** [comment]
Sorry, but I think as the issue has it's origin in the plugin / the theme. This will not be solved by HA Desktop, as it would be just a workaround and not a feature in general.
