### ISSUE TITLE
App opens in system tray, but when mouse-over on tray icon it gives the following error

### ISSUE THREAD

**Issue by KasperHoldum** [mrvnklm/homeassistant-desktop#51]
OS: Windows 11
Installation: Fresh version of 1.4 exe from release page

I tried installing and reinstalling and still get the same error: Window is not defined. It pops up first time I open the app after install, and everytime after when i hover over the systray icon.

![image](https://user-images.githubusercontent.com/921862/133627589-afdc42d0-9dc5-435c-b3b6-7819314db716.png)

**Comment by kavemang** [comment]
also getting this error as of the last week or two, I'm guessing we may have to wait for v2

**Comment by mrvnklm** [comment]
I updated all dependencies, please check if it is working with the new release.

**Comment by KasperHoldum** [comment]
Yup, fixed it for me 👌
