### ISSUE TITLE
App doesnt start on windows 10

### ISSUE THREAD

**Issue by thve25** [mrvnklm/homeassistant-desktop#57]
Hi,

I installed this app but it does not start.
The pictogram is showing in the system tray, but clicking on it doesn't do anything.

Task manager shows high memory usage.

**Comment by mrvnklm** [comment]
I updated all dependencies, please check if it is working again.

**Comment by dedors** [comment]
I just tried it, it's my first installation. Tray icon appears but can't open app. Memory keeps growing (85 to 120MB RAM in 2min, to 750MB in 2h)

**Comment by mrvnklm** [comment]
Please try to uninstall, delete the following folder and reinstall the app from the newest release.
```C:\Users\<user>\AppData\Roaming\homeassistant-desktop```

**Comment by dedors** [comment]
both 1.4.3 and 1.4.4 (with wiped appdata) don't show a tray icon anymore. Taskmanger shows 4 instances of "Home Assistant.exe", no memory increasing anymore, CPU at 0%. I'm using Win11.

**Comment by alexmnguni57** [comment]
> both 1.4.3 and 1.4.4 (with wiped appdata) don't show a tray icon anymore. Taskmanger shows 4 instances of "Home Assistant.exe", no memory increasing anymore, CPU at 0%. I'm using Win11.

I'm also experiencing the same problem. I've tried both 1.4.3 and 1.4.4 on my windows 10. No icon and I also get "a javascript error in the main process"

**Comment by mrvnklm** [comment]
Continue here https://github.com/mrvnklm/homeassistant-desktop/issues/64
