### ISSUE TITLE
All history graphs show in UTC time, not local time

### ISSUE THREAD

**Issue by abigdeel** [mrvnklm/homeassistant-desktop#58]
Just installed homeassistant-desktop a couple days ago and it has been working great for me. Running this on Windows 11 and my HA server runs in Hyper-V.

Noticed today that all history graph cards will show the time at the bottom as UTC time, not my local time. This doesn't happen when I access HA through Chrome or on mobile devices. Seems to be only happening when I use homeassistant-desktop. Not sure how long the issue has been around because it's only been a couple days that I've been using this desktop app.

I found a couple recent github issues posted about this, so it might have been caused by a recent update. It only seems to be affecting certain browsers. There's this open issue:
https://github.com/home-assistant/core/issues/57481

And there's a closed issue as well I can't find at the moment, but it was along the same lines. Was happening in a specific browser (maybe Firefox) and an update to the browser fixed it.

Hope this helps with troubleshooting somewhat.

Otherwise this works great. It will even switch over to the webRTC stream for my camera most of the time. :)

**Comment by mrvnklm** [comment]
I updated all dependencies, please check if it is working again.

**Comment by abigdeel** [comment]
Yep, showing local time now. Thanks :)
