### ISSUE TITLE
Windows 11 Interface Frozen

### ISSUE THREAD

**Issue by al3x1337** [mrvnklm/homeassistant-desktop#60]
After upgrading to Windows 11 the app has stopped working for me. I'm able to scroll up and down my Lovelace UI but any buttons on the interface including the menu bar is frozen and unclickable. 

I've "Reset Everything" multiple times now and it is persistent immediately after.

Edition	Windows 11 Education
Version	21H2
Installed on	‎2021-‎10-‎29
OS build	22000.282
Experience	Windows Feature Experience Pack 1000.22000.282.0

Anyone on Windows 11 experiencing any issues like this before I rollback to Windows 10?

**Comment by mrvnklm** [comment]
I updated all dependencies, please check if it is working again.

**Comment by abigdeel** [comment]
FYI I have a desktop and laptop that are both running Windows 11 Pro and I'm not getting this issue.

**Comment by al3x1337** [comment]
After restoring back to Windows 10 for an unrelated issue the glitch persisted.
Not sure what changed today but it seems like it resolved itself without any interaction. 
Think it was maybe a unknown windows issue.
