### ISSUE TITLE
Date and time not the same in the widget vs Home Assistant

### ISSUE THREAD

**Issue by SN0WTR00PER** [mrvnklm/homeassistant-desktop#61]
Here is 2 screen captures from statistic tabloid.

Widget : 
![image](https://user-images.githubusercontent.com/18689208/140164296-cc13d7e9-f651-41aa-a47a-d4746f7c2e3f.png)

Home Assistant :
![image](https://user-images.githubusercontent.com/18689208/140164410-33bd2aaa-1b35-4ca5-a9e4-bf8d622c771c.png)

Real time is 13:48 in home assistant, but in the widget, the time on the X scale is wrong.

**Comment by abigdeel** [comment]
Seems a lot like the bug that I reported a few weeks ago. HA-desktop was showing UTC time instead of local time.
https://github.com/mrvnklm/homeassistant-desktop/issues/58

It got resolved by @mrvnklm so this might be addressed for you as well.

**Comment by SN0WTR00PER** [comment]
> Seems a lot like the bug that I reported a few weeks ago. HA-desktop was showing UTC time instead of local time.
> https://github.com/mrvnklm/homeassistant-desktop/issues/58
> 
> It got resolved by @mrvnklm so this might be addressed for you as well.

@abigdeel Yes, I've updated to the last version and the time is correct...  THANKS for the info.
