### ISSUE TITLE
Broken on HA 2021.11.0

### ISSUE THREAD

**Issue by matt8707** [mrvnklm/homeassistant-desktop#62]
Hi, I can't log in anymore. I've tried to reset and reinstall. I saw that v2 is coming but is there any chance to push a hotfix? Really miss not having the keyboard shortcuts and whatnot. Thanks!

**Comment by hhergeth** [comment]
After upgrading to 2021.11.0 I am getting an infinite loading circle with the message "Loading Data". Also tried resetting the whole application.

**Comment by mrvnklm** [comment]
I updated all dependencies, please check if it is working again.

**Comment by matt8707** [comment]
Thanks, It's working!
