### ISSUE TITLE
can`t start on win 11

### ISSUE THREAD

**Issue by userosos** [mrvnklm/homeassistant-desktop#64]
Hi! After install HA-d don`t start. See pic.
![изображение](https://user-images.githubusercontent.com/22872748/140621884-1e73cf87-8398-43f3-b3b7-451b509565ae.png)

**Comment by mrvnklm** [comment]
Please check the new release.

**Comment by userosos** [comment]
> Please check the new release.

![изображение](https://user-images.githubusercontent.com/22872748/140648721-26983d8a-b511-4311-bcd6-c683cc17ff50.png)

**Comment by maxtheobald** [comment]
Same problem here (Win 11 Dev and V1.45)

**Comment by thehedgefrog** [comment]
Same issue with 1.4.5 on Win 10 21H1.

**Comment by mrvnklm** [comment]
Okay, I need to get a windows mashine tomorrow, so I can debug that issue.

**Comment by josrafafonlo** [comment]
I just had that exact problem on windows 10 and managed to solve it.
Don't know if this is important but I had "always show all icons on the notification area" setting enabled, so I had no "tray" per se. I started by disabling that but to no avail. 
I then installed 1.4.0 version wich worked, and by default it comes with "autoupdate" ticked so after around one minute (it happened while I was logging in into hass) it closed and updated to latest (1.4.5) wich now is working without problems.

**Comment by mrvnklm** [comment]
> I just had that exact problem on windows 10 and managed to solve it. Don't know if this is important but I had "always show all icons on the notification area" setting enabled, so I had no "tray" per se. I started by disabling that but to no avail. I then installed 1.4.0 version wich worked, and by default it comes with "autoupdate" ticked so after around one minute (it happened while I was logging in into hass) it closed and updated to latest (1.4.5) wich now is working without problems.

Thank you, that helped me a lot to debug the issue which will be fixed in the upcoming release.

**Comment by dedors** [comment]
1.4.5, tray icon is there but don't interact. Memory increasing by ~20MB/min. I deleted AppData\Roaming\homeassistant-desktop beforehand. There is constantly appearing a config.json.tmp-ID file, disappearing right away and creating the next one.
