### ISSUE TITLE
Can't interact with tray icon in Windows 11 after latest update

### ISSUE THREAD

**Issue by KasperHoldum** [mrvnklm/homeassistant-desktop#65]
The app opens and sits in the tray, but it is no longer possible to interact with the icon (hovering, clicking, right clicking). Nothing happens and eventually the app crashes and disappears.

This is after working working before the newest update.

**Comment by maxtheobald** [comment]
Same problem here (Win 11 Dev and V1.45)

**Comment by mrvnklm** [comment]
Continue here https://github.com/mrvnklm/homeassistant-desktop/issues/64
